---
abstract: 'Set Data::Dumper indent'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Any-Adapter-Core-Patch-SetDumperIndent
requires:
  Log::Any: 0.14
  Module::Patch: 0.12
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Log-Any-Adapter-Core-Patch-SetDumperIndent
  repository: http://github.com/sharyanto/perl-Log-Any-Adapter-Core-Patch-SetDumperIndent
version: 0.01
